version: '2'
services:
  collectdamazon2017:
    build:
      context: ..
      dockerfile: integration_test/Dockerfile.collectd.amazon2017.03
    environment:
      SF_API_TOKEN: testing
      SF_INGEST_TOKEN: fake_sfx
    depends_on:
      - fake_sfx
      - couchdb210
    
  couchdb210:
    image: apache/couchdb:2.1.0
    ports:
      - 5984

  fake_sfx:
    build:
      context: .
      dockerfile: Dockerfile.sink

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
        - collectdamazon2017